### ISSUE TITLE
Landing Page

### ISSUE THREAD

**Issue by kahluamascara** [adam-edison/game-server#1]
### Issue Description:
* Design and create the page a user sees when they first log in to the system.

### Requirements
* Link to the user profile
* Link to the user lounge
* Display current balance of in-game currency
* Display "featured fundraising project" progress bar
* Invitations sidebar (collapsible, with red-circle notification) - for multiplayer features
* Game search area
  * Search/Filter for Games by Genre, Single/Multiplayer, Name (with autocomplete)
  * Click on a game from search results to play your game
  * Click on an invitation to join a multiplayer game waiting for the user
* Main display area
  * Slideshow of all fundraising projects
  * Slideshow includes ways to earn extra points

**Comment by kahluamascara** [comment]
![landing page](https://user-images.githubusercontent.com/47229051/52661575-5ecbca80-2ed0-11e9-87a4-71af94f13fb9.jpg)

**Comment by adam-edison** [comment]
I was looking for something in between what you just posted, and this:

![image](https://user-images.githubusercontent.com/15655308/52825988-fd048f80-308c-11e9-962e-fe881bdbe025.png)

**Comment by adam-edison** [comment]
Also, I think what you have doesn't have enough going on. But Steam has too much going on:

![image](https://user-images.githubusercontent.com/15655308/52826181-dabf4180-308d-11e9-9750-0e90a0096764.png)

**Comment by adam-edison** [comment]
> Overworld interface with links to assortment of games

Test reply

**Comment by kahluamascara** [comment]
![ss_dfc35919317347c5d9bea943adc3b5a53476f170 1920x1080](https://user-images.githubusercontent.com/47229051/52826384-97190780-308e-11e9-9aa7-e3d155539c80.jpg)

**Comment by kahluamascara** [comment]
![landing pages](https://user-images.githubusercontent.com/47229051/53208324-62fc9400-3604-11e9-9d14-9634a2f5a715.jpg)

**Comment by adam-edison** [comment]
The bottom multiplayer toolbar should be sticky. That's for a future note.

**Comment by adam-edison** [comment]
@ryanvalperga We could create this landing page without using React - easily using traditional CSS, JS, BootStrap, and maybe handlebars as a templating engine.  However, I'm not sure if that's a good idea. We might want to make our entire site an SPA, rather than mix and match. This way client-side concerns stay together.

**Comment by adam-edison** [comment]
However, that means constant network traffic fetching data back-and-forth to the client (which I guess would be unavoidable anyway for a multiplayer game) or using sockets if we need real-time control.

**Comment by adam-edison** [comment]
Approaches we can try:

* [Using react on client-side, and react router and express on node side](https://dev.to/nburgess/creating-a-react-app-with-react-router-and-an-express-backend-33l3)
* [Using react, webpack, babel, express, node](https://www.byteconf.com/blog/building-a-full-stack-application-with-react-and-node)

**Comment by adam-edison** [comment]
Also, this article is hilarious, and illustrates some of the TDD approach we want to use:

* https://medium.com/@houstoncbreedlove/basics-intro-to-testing-react-components-with-mocha-chai-enzyme-and-sinon-c8b82ce58df8

And this one is just an interesting article on the same topic:

* https://medium.freecodecamp.org/quick-guide-to-tdd-in-react-81888be67c64

**Comment by adam-edison** [comment]
I think for the Landing Page (and later login stuff, etc) it makes the most sense to keep it simple and just use a server-side templating engine like handlebars. Simple html, css, js.

**Comment by adam-edison** [comment]
It appears that due to the flexibility of `express` we can set some routes to be served statically, others to render templates, and others to be "react routes".

**Comment by ryanvalperga** [comment]
The landing page may need react for showing when people are requesting a game without the need to reload the page.

**Comment by adam-edison** [comment]
In that case, let's just use `React` site-wide, so that we have reusable components across the entire site. And it would simplify things a bit, because the entire site would be one giant SPA, instead of some parts being a MPA and others being an SPA.

**Comment by adam-edison** [comment]
Consulted with Khorram. He says that SPA may be OK to start, but if the game becomes large (like an RPG with hundreds of concurrent users), we might want to consider an MPA - one page for login, one page for status, etc, and one page to play the game). It's also beneficial to have multiple SPAs driven by the MPA if we intend to package the games later to a different medium (like a mobile device using React Native).

**Comment by adam-edison** [comment]
Rather than polling with jQuery or React, we could use web sockets to push data to the client with node.
* https://socket.io/get-started/chat/

That could handle the "you've been invited to a game" without a 1-2 sec delay or tons of requests going back and forth to the server. It's just event listening.

**Comment by adam-edison** [comment]
Khorram and I also agree that Next.js is a good move for the Landing Page, once we're ready, to improve performance.   

But outside of the "logged-in" area, server-side templating would be best - and would allow user authentication to occur at the server level.

Inside the "logged-in" area, SPA is best - it will help us seamlessly move from browsing games, accepting invitations from friends, or entering a game.

**Comment by adam-edison** [comment]
Khorram recommends using state hooks and content-blocking resolutions so that while the landing page is loading, common game components (to all games) can load in the background. Then, when the user selects a game, we can load the game-specific components on-demand.
