### ISSUE TITLE
User 'Lounge'

### ISSUE THREAD

**Issue by kahluamascara** [adam-edison/game-server#2]
Personal screen for collectibles

**Comment by kahluamascara** [comment]
![lounge](https://user-images.githubusercontent.com/47229051/53208599-617f9b80-3605-11e9-9cce-a657a6039fe2.jpg)

**Comment by adam-edison** [comment]
We just need a way to get back to the landing page and/or account.  
I would suggest maybe that top bar is the same top-bar as from the landing page. 
That gives you freedom on the entire rest of the page.
