### ISSUE TITLE
Game Lobby

### ISSUE THREAD

**Issue by kahluamascara** [adam-edison/game-server#6]
![gamelobby2](https://user-images.githubusercontent.com/47229051/53999141-5bfb7880-4110-11e9-8a59-d2c7025cf42b.jpg)

**Comment by adam-edison** [comment]
Supports 1 to n players, where n is the max supported by the game.  
Number of teams allowed is also defined by the game.

**Comment by adam-edison** [comment]
The team box next to the name is a good idea - number would work. That eliminates any concern with drag and drop on mobile browsers.
